### PR TITLE
Improved language/locale support

### PR DESCRIPTION
**Pull request by patrickmaurer**
Created a more complete language mapping based on the MSDN article link inside the script (excel file for easier updating included -> copy paste output to ps1 script). Also added 3010 as valid exit code (reboot required).

### CODE REVIEW

**Comment by shureek** [comment]
How on earth did you find direct download url? I wanted to add support for russian (1049), but it didn't work.

**Comment by shureek** [comment]
I found it. But there is no russian installer 11.0.10, only 11.0.00. It seems that you need to update it after installation. Too bad.

**Comment by ferventcoder** [comment]
@patrickmaurer found those. Hmmm that's not fun.

**Comment by patrickmaurer** [comment]
As you probably already discovered, I used this page to get the URLs: http://get.adobe.com/reader/otherversions/

I also noticed, that only a handful of languages (those included in this package) are getting minor updates. Many languages stay behind at 11.0.0 it seems...

**Comment by patrickmaurer** [comment]
To support more languages, we would have to change this package to install 11.0 and then update (at least for languages without a "direct" installer). Or maybe better switch to the MUI installer.

http://www.adobe.com/support/downloads/product.jsp?platform=windows&product=10

**Pull request merged**
