### PR TITLE
(vim) Removed package

### PR DESCRIPTION
**Pull request by matsuhav**
The package is outdated and I wrote a AU script to update from [vim-win32-installer](https://github.com/vim/vim-win32-installer).
This is a official build from vim.org and updated nightly.
Currently, there are no packages on chocolatey to install official build.

This repository seems to not support AU, I made a PR on [Core Team Repo](https://github.com/chocolatey-community/chocolatey-coreteampackages)
The corresponding PR is https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1335.

At first I submitted as a different package to community but, thanks to @gep13 , I made this PR.
The package is [here](https://chocolatey.org/packages/vim-latest/). I will delete this after this PR closed.

There is another vim PR #304 .

### CODE REVIEW

**Comment by gep13** [comment]
@matsuhav  Can you please update this PR to not delete the icon file?

This will prevent the icon from appearing (potentially) as broken on older package versions.

**Comment by matsuhav** [comment]
I updated to not delete the icon file.

**Comment by gep13** [comment]
@matsuhav perfect, thank you for doing this!  I have reached out to @ferventcoder to have a final look over this, and once I have his approval, I will get this PR merged, and the chocolatey user added to vim package, so that new updates can continue to be pushed out.

**Comment by gep13** [comment]
@matsuhav thank you for taking the time to do that.  Your changes have been merged, thanks for your contribution 👍

**Pull request merged**
