### PR TITLE
Fix 404 error for Jetty download 

### PR DESCRIPTION
**Pull request by Nilzor**
Switch from server `mirror.cologne.de` who's obviously stopped mirroring, to `eclipse.org`

### CODE REVIEW

**Comment by ferventcoder** [comment]
Already pushed?

**Comment by Nilzor** [comment]
No it's not pushed manually. I was unsure if it would collide with the automatic push routine (I haven't set up automatic pushing from my machine). Could you please run the script?

So just to be clear, the current pushed & approved version of Jetty in Chocolatey yields 404 Jetty 9.3.6.20151106 , but there is a version 9.3.7 which would be pushed once you run the ketarin script

**Comment by ferventcoder** [comment]
The ketarin script would have already run multiple times a day by now since this was merged.

**Comment by ferventcoder** [comment]
Something went wrong in the push, I pushed it.

**Pull request merged**
