### PR TITLE
#73 - Fix for VLC

### LINKED ISSUE #73: VLC should move to "get.videolan.org" instead of "downloads"
https://twitter.com/etixxx/status/607854498451591168

### PR DESCRIPTION
**Pull request by DanAtkinson**
As per https://twitter.com/etixxx/status/607854498451591168.

Should resolve #73.

### CODE REVIEW

**Comment by ferventcoder** [comment]
ketarin updated.

**Comment by DanAtkinson** [comment]
Thanks. How long between Ketarin being updated and the changes taking effect on the site? I would have expected the notepadplusplus.install to pick up the missing package is all.

**Comment by ferventcoder** [comment]
Looks updated to me.

**Comment by ferventcoder** [comment]
The length of time between updating ketarin and me running it in ketarin is what it was. :) 

I should have used the term "imported into Ketarin". :D

**Pull request merged**
