### PR TITLE
(git*) migrated to coreteam repository

### PR DESCRIPTION
**Pull request by pascalberger**
Should be merged after deprecation of the `git.commandline` package: https://github.com/ferventcoder/chocolatey-packages/pull/225

PR for integration in the core team repo: https://github.com/chocolatey/chocolatey-coreteampackages/pull/489

### CODE REVIEW

**Comment by ferventcoder** [comment]
Let's not delete the _output folder just yet - I'm in the middle of https://github.com/ferventcoder/chocolatey-packages/issues/200

**Comment by ferventcoder** [comment]
For removing the other folders, let's move forward with that - let me know when you've updated this so Gary or I can merge it. Thanks!

**Comment by gep13** [comment]
Phew!  I was literally just about to merge this 😄 

I will hold off until I hear it has been updated.

**Comment by majkinetor** [comment]
I am about to merge Git on core. Please merge here.

**Comment by pascalberger** [comment]
@ferventcoder Done

**Pull request merged**
