### PR TITLE
migrated to coreteamrepo

### PR DESCRIPTION
**Pull request by majkinetor**
https://github.com/chocolatey/chocolatey-coreteampackages/pull/864

### CODE REVIEW

**Comment by ferventcoder** [comment]
I didn't think we were removing older versions from this repo, and it looks like you may have missed the filezilla ketarin file(s) in https://github.com/ferventcoder/chocolatey-packages/tree/master/ketarin.

**Comment by gep13** [comment]
@majkinetor are you in a position to update this?

**Comment by gep13** [comment]
@majkinetor ?

**Comment by majkinetor** [comment]
Extremely no time ATM. Sorry.

**Comment by gep13** [comment]
I am going to go ahead and close this out, as I believe I have taken care of this directly.

**Pull request closed without merging**
