### PR TITLE
deprecate googledrive

### PR DESCRIPTION
**Pull request by jacktose**
Google no longer supports the Drive desktop app.
Replaced by [google-backup-and-sync](https://chocolatey.org/packages/google-backup-and-sync) and [google-drive-file-stream](https://chocolatey.org/packages/google-drive-file-stream).

### CODE REVIEW

**Comment by hsellik** [comment]
@gep13 , could you take a look at this? New user to chocolatey. I find it awesome, but I wasted like half an hour on finding out why the google drive was not working.

**Comment by jacktose** [comment]
@ferventcoder or @gep13 can we finish this?

**Comment by BlythMeister** [comment]
Rather than merge this, can we update it to be the actual google drive installer: https://www.google.com/drive/download/

Whereas at the moment this is an old google back/sync which is a differetn application

**Comment by jacktose** [comment]
Agreed. This took so long, Google realigned their products again! 😆

**Pull request closed without merging**
