### PR TITLE
(Launchy) Updated to v2.6.0-beta2

### PR DESCRIPTION
**Pull request by virtualex-itv**

### CODE REVIEW

**Comment by gep13** [comment]
@virtualex-itv while I am happy to get this merged, I thought the intention was for you to move this into your own repository?  Or did I misunderstand that?  Ideally, this would be updated to use AU within your repository, assuming you are set up for that.

**Comment by virtualex-itv** [comment]
i guess we had a misunderstanding...I do also have this in my own [repository](https://github.com/virtualex-itv/choco-launchy) which I manage manually as I do not leverage AU.  Since I co-maintain and do not fully own the package, I didn't think it should've been removed hence why I also submitted my changes here so the main repo could be updated.  This package is also manually maintained in this github repo and is not updated via AU.  I doubt we'll see anymore updates for this app.

**Comment by gep13** [comment]
@virtualex-itv sounds like a plan.  I will get this done, thanks!

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@virtualex-itv your changes have been merged, thanks for your contribution 👍

**Pull request merged**
