### PR TITLE
(foobar2000) Fixes for foobar2000

### PR DESCRIPTION
**Pull request by AeliusSaionji**
-Scrapes the official site for an official download link. No more relying on filehippo
-Minor updates  to nuspec

### CODE REVIEW

**Comment by ferventcoder** [comment]
Good start - still needs the ketarin updates and then the checksum additions ;)

**Comment by Link-Satonaka** [comment]
Would AU be preferred at this point?

**Comment by ferventcoder** [comment]
Yes, AU would be preferred. I need to spend some time getting AU set up.

**Comment by majkinetor** [comment]
@Link-Satonaka 

Why not move this to core where AU is already setup.

**Comment by AeliusSaionji** [comment]
Looks like this package has a) changed hands and b) now just embeds the installer in the package itself.

**Pull request closed without merging**
