### PR TITLE
(paint.net) refresh

### PR DESCRIPTION
**Pull request by Link-Satonaka**
No real changes, just follows the guidelines and latest templates. Added some details to nuspec.

### CODE REVIEW

**Comment by ferventcoder** [comment]
Looks pretty good - missing one important detail - it requires .net 3.5 installed.

**Comment by Link-Satonaka** [comment]
Did not know that! Fixed

**Comment by Link-Satonaka** [comment]
http://www.getpaint.net/download.html
Hm actually it depends on dotnet 4.6 (and the URL points to 4.6.1), and there appears to be multiple 4.6 dotnets in the chocolatey repo. Not sure how to proceed.

**Comment by onlytherain** [comment]
You may find following registry queries useful. Maybe you could point to an appropriate dotnet version depending on the result(s) of these queries. They simply return the version of a currently installed dotnet family.

(for NetFX v3.5.x):
`reg query "HKLM\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5\Full" /v Version`

(for NetFX v4.x.x):
`reg query "HKLM\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full" /v Version`

An example result when dotnet 4.6 is installed:
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full
Version    REG_SZ    4.6.00081
```
Cheers.

**Comment by Link-Satonaka** [comment]
Note for myself:

this is a dependency for dotnet4.6.1 for Win8, which the verifier box does not have at the moment.
https://support.microsoft.com/en-us/kb/2919355

I'll do it eventually if necessary. Would need to be added as a dependency of the dotnet4.6.1 package.

**Comment by ferventcoder** [comment]
Weird, it doesn't seem to like something here...

**Comment by ferventcoder** [comment]
Sorry, meant that this can't automatically be merged currently.

**Comment by Link-Satonaka** [comment]
Yeah I saw that, but it isn't telling me what is conflicting. Not sure how to save this, probably need to make a new PR?

**Comment by ferventcoder** [comment]
Git fetch
git rebase

That should help you fix any issues.

**Comment by ferventcoder** [comment]
git checkout master
Git fetch thisreporemote
git rebase thisreporemote/master
git checkout paintdotnet
git rebase master

**Comment by gep13** [comment]
@Link-Satonaka I believe I am correct in saying that the Paint.Net package has been moved over to this repository:

https://github.com/chocolatey/chocolatey-coreteampackages

As such, I am going to close this PR.  Please let me know if you have any questions.

**Pull request closed without merging**
