### PR TITLE
Support optional InstallDir parameter.

### PR DESCRIPTION
**Pull request by jdshkolnik**
#264

### CODE REVIEW

**Comment by jdshkolnik** [comment]
@ferventcoder Which version would the dependency be for? 1.3.3?

**Comment by ferventcoder** [comment]
@jdshkolnik whatever the others use, if you add it as a minimum dependency, then it will use at least that (e.g. `<dependency id="chocolatey-core.extension" version="1.1.0" />`). Best to follow the advice  at https://chocolatey.org/docs/how-to-parse-package-parameters-argument#built-in

**Comment by jdshkolnik** [comment]
Dependency added.

**Comment by ferventcoder** [comment]
Thanks!

**Pull request merged**
