### PR TITLE
(synergy) free version (v1.4.18)

### PR DESCRIPTION
**Pull request by cspotcode**
This is the version of Synergy that is still freely downloadable from Symless's website.  I'm no Chocolatey expert and I haven't tested this.

### CODE REVIEW

**Comment by ferventcoder** [comment]
What is symless?

**Comment by ferventcoder** [comment]
Unfortunately this doesn't come from the original distribution point, I'm not sure we'd pull it in as is. Are the newer versions no longer free?

**Comment by cspotcode** [comment]
Symless appears to be the company behind Synergy.  See their [about page](http://symless.com/about).

The download page asks for a one-time payment of $10 for the basic version even though it's still open-source, so there's nothing stopping someone else from building it and distributing binaries elsewhere.

**Comment by ferventcoder** [comment]
Must have been a more recent thing. 👍

**Comment by gep13** [comment]
This package is now being maintained in this repository:

https://github.com/teknowledgist/Chocolatey-packages/tree/master/discontinued/synergy

As such, I am going to go ahead and close out this PR.

**Pull request closed without merging**
