### PR TITLE
Update Synergy to 1.7.3

### PR DESCRIPTION
**Pull request by miketweaver**
I'd like to help update Synergy to 1.7.3

### CODE REVIEW

**Comment by ferventcoder** [comment]
They are available for download again? For awhile those were not working - also you need to update the version in the nuspec. :)

**Comment by miketweaver** [comment]
Yes. They're pretty hidden, it took some major googlefu to find the right naming scheme, but the downloads work. 

Thanks for the catch with the nuspec. It slipped right past me. That's what I get for editing the code on github's website directly instead of pushing my local files up.

Note: I *have* tested this on a fresh x64 and it works just great.

**Comment by miketweaver** [comment]
How's this looking to be accepted?

**Comment by ferventcoder** [comment]
Thanks for the reminder.

**Comment by ferventcoder** [comment]
pushed and waiting on moderation.

**Comment by ferventcoder** [comment]
Thanks for the contribution!

**Pull request merged**
