### PR TITLE
Update Ruby2.DevKit URLs as cdn.rubyinstaller.org is down

### PR DESCRIPTION
**Pull request by vivobg**

### CODE REVIEW

**Comment by martynakaminska** [comment]
👍

**Comment by zymzxq** [comment]
Any update on the pr?

**Comment by ElanHasson** [comment]
When can this get merged?

**Comment by gep13** [comment]
@vivobg thank you for taking the time to make this change!

**Comment by denishonig** [comment]
Hi! 
When will be update for package? In other words - when the following command will work:
choco install ruby2.devkit -version 4.7.2.2013022402 -source https://chocolatey.org/api/v2/ -y --allowEmptyChecksums

Thanks

**Comment by gep13** [comment]
@denishonig this PR was created because the installation URL's in package version 4.7.2.2013022402 was wrong.  Since package versions are immutable, meaning that they can't be changed, using:

```
choco install ruby2.devkit -version 4.7.2.2013022402 -source https://chocolatey.org/api/v2/ -y --allowEmptyChecksums
```

will no always fail, unless those download URL's are re-instated, which is unlikely.  However, as a result on this PR, there is a new package version available here:

https://chocolatey.org/packages/ruby2.devkit/4.7.2.2013022403

So you should be able to use:

```
choco install ruby2.devkit -version 4.7.2.2013022403
```

Hope this helps!

**Pull request merged**
