### PR TITLE
Download putty using https

### PR DESCRIPTION
**Pull request by cmorty**

### CODE REVIEW

**Comment by ferventcoder** [comment]
Wow, when did they make https available?

**Comment by cmorty** [comment]
@ferventcoder Don't know, but all the links at http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html go to https. They also provide MSI-Packages. And on the long run one probably wants to check the signatures,  but I'm new to Chocolatey and changing to https seemed a simple enough thing to do for starters. :)

**Comment by ferventcoder** [comment]
Looks good to me!

**Comment by ferventcoder** [comment]
Thanks for the contribution!

**Pull request merged**
