### PR TITLE
Removed Dropbox as it's pending approval in the core-team-packages

### PR DESCRIPTION
**Pull request by The-Running-Dev**

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
@ferventcoder any chance of getting this merged?
The PR https://github.com/chocolatey/chocolatey-coreteampackages/pull/664 is ready to be merged, only waiting for it to be removed from this repo.

**Comment by gep13** [comment]
I forget... should we also be deleting the ketarin.xml file as well?

**Comment by gep13** [comment]
@AdmiringWorm ^^

**Comment by AdmiringWorm** [comment]
@gep13 oh right, I forgot you also could merge PR's here.
Yeah, I believe the ketarin file also have to be removed.

**Comment by AdmiringWorm** [comment]
@gep13 yup, from the core team repo's migration docs.
- Remove the ketarin.*.xml file.

Everything should be removed, except the icon.

**Comment by AdmiringWorm** [comment]
It also actually mentiones: `If the _output folder is checked into the repository, delete the folder associated with the package.`

**Comment by gep13** [comment]
@AdmiringWorm that last one I will wait on @ferventcoder commenting on.  I seem to remember him requesting that this NOT be done, but I could be remembering something else.

**Pull request merged**
