### PR TITLE
(vagrant) migrated to coreteam repository

### PR DESCRIPTION
**Pull request by majkinetor**

### CODE REVIEW

**Comment by majkinetor** [comment]
This is merged at core, please merge this one.

**Comment by gep13** [comment]
@majkinetor for future migrations, it would be best to not merge into the Core Team Packages repo until the PR into this Repo is completed.

**Comment by majkinetor** [comment]
For future migrations, it would be best you guys to be more agile. This is not rocket science.

**Comment by gep13** [comment]
>@majkinetor said...
For future migrations, it would be best you guys to be more agile. This is not rocket science.

Can you explain that?

**Pull request merged**
