### PR TITLE
Fix install dependency vcredist2010

### PR DESCRIPTION
**Pull request by rogeriopradoj**
As pointed in https://chocolatey.org/packages/vagrant#comment-2524313735 and https://github.com/mitchellh/vagrant/issues/6754

### CODE REVIEW

**Comment by ferventcoder** [comment]
Thanks!

**Comment by ferventcoder** [comment]
Do we need to fix the current version?

**Comment by rogeriopradoj** [comment]
I think it's is a good idea: 1.8.1.20160219 could be great, don't you think?

**Comment by lmakarov** [comment]
This is still an issue with v1.8.1 from chocolatey.

```
vagrant init debian/jessie64
...
vagrant up
...
The box 'debian/jessie64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/debian/jessie64"]
Error:
```

**Comment by ferventcoder** [comment]
@lmakarov Copy pasta bad?

**Comment by ferventcoder** [comment]
@lmakarov we haven't shipped a subsequent version yet.

**Comment by ferventcoder** [comment]
Thanks for the reminder though, I just pushed it up.

**Pull request merged**
