### PR TITLE
(skype) (GH-102) Skype Package Fixes

### PR DESCRIPTION
**Pull request by cpmcgrath**
Download Skype before uninstalling. If it's a update, don't add the RemoveStartup parameter (respect existing settings). Also got rid of Write-ChocolateyFailure which it complained was obsolete.
#102

### CODE REVIEW

**Comment by ferventcoder** [comment]
This looks pretty good - I'm going to look at it a little closer to try to understand why functions were necessary. I'm guessing there may have been something the framework isn't/wasn't doing correctly? 

With these scripts I try to have one flow so it's super easy to follow - functions break that up a bit. It's likely even more difficult for folks reviewing a script at runtime to decide if they want to run it or not.

**Comment by cpmcgrath** [comment]
The functions aren't needed, It was just to keep the code clean. There were a few things which I had to do which wasn't needed in the Install-ChocolateyPackage
1. The Join-Path $env:TEMP 'chocolatey' - In Install-ChocolateyPackage $env:Temp already contained the \chocolatey
2. COALESCE on the filepath. Get-ChocolateyWebFile was returning null for me, so I coalesced the result with the file variable that we passed into Get-ChocolateyWebFile.

**Comment by ferventcoder** [comment]
> 2. COALESCE on the filepath. Get-ChocolateyWebFile was returning null for me, so I coalesced the result with the file variable that we passed into Get-ChocolateyWebFile.

What version of choco? I wonder if this is a bug?

**Comment by ferventcoder** [comment]
`-getOriginalFileName` only works in 0.9.10+, which is still in beta.

**Comment by cpmcgrath** [comment]
Ah, I was looking at the Master branch for how Install-ChocolateyPackage works. Should have looked at the latest released code.

**Comment by cpmcgrath** [comment]
Just had a look at the 0.9.9.12 version of Install-ChocolateyPackage.
The new things I use from the beta just get ignored in the latest release (as long as you have the coalesce), so I don't think a change is needed.

Let me know if there's anything you want me to change.

**Comment by ferventcoder** [comment]
:)

**Comment by ferventcoder** [comment]
Wow, apologies on not getting back to this sooner. I need to make some time to revisit this in the coming weeks.

**Comment by ferventcoder** [comment]
Closing, this was pulled over to a different repository.

**Pull request closed without merging**
