### PR TITLE
(vlc) moved to coreteam packages

### PR DESCRIPTION
**Pull request by majkinetor**
Checksum was failing so I updated it and modernized it and moved it to the core repo in the process.

After merging don't forget to remove it from your ketarin schedule. You may want to consult @gep13 who made changes to core setup so that once ketarin files are removed from the repo local runner synchronizes.

https://github.com/chocolatey/chocolatey-coreteampackages/pull/417

### CODE REVIEW

**Comment by ferventcoder** [comment]
Remove everything. Leave the icon folder.

**Comment by majkinetor** [comment]
I removed everything and icon file.

**Comment by majkinetor** [comment]
Or u ment that i should do so in general in advance.

**Comment by ferventcoder** [comment]
leave the icon i the future

**Comment by majkinetor** [comment]
Ok

**Comment by majkinetor** [comment]
Icon restored

**Pull request merged**
